-- MySQL Script generated by MySQL Workbench
-- Tue Jan 18 10:21:32 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema wedding_planner
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema wedding_planner
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `wedding_planner` DEFAULT CHARACTER SET utf8 ;
USE `wedding_planner` ;

-- -----------------------------------------------------
-- Table `wedding_planner`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`category` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`category` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `picture_url` TEXT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`service` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`service` (
  `id` INT NOT NULL,
  `category_id` INT NULL,
  `picture_url` TEXT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `contact_person` VARCHAR(255) NULL,
  `contact_phone` VARCHAR(45) NULL,
  `contact_email` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_category_idx` (`category_id` ASC) VISIBLE,
  CONSTRAINT `fk_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `wedding_planner`.`category` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`currency`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`currency` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`currency` (
  `id` INT NOT NULL,
  `country` VARCHAR(255) NULL,
  `short_id` VARCHAR(3) NULL,
  `rate` FLOAT(8,2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`service_package`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`service_package` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`service_package` (
  `id` INT NOT NULL,
  `service_id` INT NULL,
  `name` VARCHAR(255) NULL,
  `description` TEXT NULL,
  `price` FLOAT NULL,
  `price_currency_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_idx` (`service_id` ASC) VISIBLE,
  INDEX `fk_currency_idx` (`price_currency_id` ASC) VISIBLE,
  CONSTRAINT `fk_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `wedding_planner`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_currency`
    FOREIGN KEY (`price_currency_id`)
    REFERENCES `wedding_planner`.`currency` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`package_availability`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`package_availability` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`package_availability` (
  `id` INT NOT NULL,
  `service_package_id` INT NULL,
  `available_from` DATETIME NULL,
  `available_to` DATETIME NULL,
  `available_on_day` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_package_id_idx` (`service_package_id` ASC) VISIBLE,
  CONSTRAINT `fk_package_id`
    FOREIGN KEY (`service_package_id`)
    REFERENCES `wedding_planner`.`service_package` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`event`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`event` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`event` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  `date` DATETIME NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`event_service`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`event_service` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`event_service` (
  `id` INT NOT NULL,
  `event_id` INT NULL,
  `service_id` INT NULL,
  `selected` BIT(1) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_service_idx` (`service_id` ASC) VISIBLE,
  INDEX `fk_event_idx` (`event_id` ASC) VISIBLE,
  CONSTRAINT `fk_service`
    FOREIGN KEY (`service_id`)
    REFERENCES `wedding_planner`.`service` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `wedding_planner`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`role` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`user` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`user` (
  `id` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `password` VARCHAR(150) NULL,
  `email` VARCHAR(150) NULL,
  `role_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_role_id_idx` (`role_id` ASC) VISIBLE,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `wedding_planner`.`role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`user_event_role`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`user_event_role` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`user_event_role` (
  `id` INT NOT NULL,
  `name` VARCHAR(255) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `wedding_planner`.`event_user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `wedding_planner`.`event_user` ;

CREATE TABLE IF NOT EXISTS `wedding_planner`.`event_user` (
  `id` INT NOT NULL,
  `event_id` INT NULL,
  `user_id` INT NULL,
  `event_role_id` INT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_event_idx` (`event_id` ASC) VISIBLE,
  INDEX `fk_user_id_idx` (`user_id` ASC) VISIBLE,
  INDEX `fk_event_role_idx` (`event_role_id` ASC) VISIBLE,
  CONSTRAINT `fk_event`
    FOREIGN KEY (`event_id`)
    REFERENCES `wedding_planner`.`event` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `wedding_planner`.`user` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_event_role`
    FOREIGN KEY (`event_role_id`)
    REFERENCES `wedding_planner`.`user_event_role` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
